### ISSUE TITLE
Cloudflare email protection display bug on /projects/ page

### ISSUE THREAD

**Issue by JamieOnUbuntu** [VulnHive/vulnhive.com#2]
When browsing the website with JavaScript disabled, the email protection on the /projects/ page displays incorrectly:

`[email protected]ve.com`

It should display as:

`[email protected]`

I have been able to recreate this with Chromium + Tor Browser on Linux and MobileSafari on iOS. This issue only seems to affect the /projects/ page.

![image](https://user-images.githubusercontent.com/10353998/36126460-77572e36-1050-11e8-92b0-b9a6e70eb83b.png)

`<li><a class="u-email" href="/cdn-cgi/l/email-protection#redacted"><span class="__cf_email__" data-cfemail="redacted">[email&#160;protected]</span>ve.com</a></li>`

**Comment by EdOverflow** [comment]
Thank you for bringing this to my attention, @JamieOnUbuntu. I disabled the _"Email Address Obfuscation"_ feature on Cloudflare now.

**Comment by JamieOnUbuntu** [comment]
Thanks Ed. I wasn't necessarily suggesting that you disable the Cloudflare email obfuscation, I was just pointing out the display issue on one of the pages. I thought it was intended to be enabled.

I guess if you didn't intend to have the email obfuscation enabled then that's OK :)
